name: Binary Release Builder

on:
  release:
    types:
      - published

jobs:
  build-linux:
    name: Build for Linux (x86_64, ARM64)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform }}

      - name: Install Dependencies for Linux ARM
        if: matrix.platform == 'aarch64-unknown-linux-gnu'
        run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu

      - name: Set up Cargo for Linux ARM
        if: matrix.platform == 'aarch64-unknown-linux-gnu'
        run: |
          mkdir -p ~/.cargo
          echo '[target.aarch64-unknown-linux-gnu]' >> ~/.cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml

      - name: Build and Package
        run: |
          cargo build --target ${{ matrix.platform }} --release
          cd target/${{ matrix.platform }}/release/
          rm -rf $(ls | grep -v -E '^(scal|sdate|sstat)$')
          zip -r ${{ matrix.platform }}.zip ./*

      - name: Upload File to Assets
        uses: softprops/action-gh-release@v3
        with:
          files: target/${{ matrix.platform }}/release/${{ matrix.platform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build for macOS (x86_64, ARM64)
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform }}

      - name: Build and Package
        run: |
          cargo build --target ${{ matrix.platform }} --release
          cd target/${{ matrix.platform }}/release/
          rm -rf $(ls | grep -v -E '^(scal|sdate|sstat)$')
          zip -r ${{ matrix.platform }}.zip ./*

      - name: Upload File to Assets
        uses: softprops/action-gh-release@v3
        with:
          files: target/${{ matrix.platform }}/release/${{ matrix.platform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
